galaxy_info:
  author: IBM
  description: Role that shows all static routes
  company: IBM

  license: Apache

  min_ansible_version: 2.7

  galaxy_tags:
  - isam
  - ibm
  - networking
  - static route
  - add

dependencies:
  - start_config
