---
#todo: the ibmsecurity.isam.aac.scim.get_all is missing actually
- name: Get Scim Config
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.scim.get_all
    isamapi:
  register: ret_obj

- name    : Set variable get_scim for use by rest of playbook
  set_fact:
    get_scim: "{{ ret_obj.data | default([]) }}"
    unique_code: "{{ 10000 | random }}"

- name: Make sure destination directory "{{ export_dir }}/{{ unique_code }}" exists
  become: "{{ ansible_use_become | default(false) }}"
  file  :
     path   : "{{ export_dir }}/{{ unique_code }}"
     state  : directory
     mode   : "{{ ansible_group_mode | default( omit ) }}"
     group  : "{{ ansible_group_for_administrators | default( omit ) }}"
     recurse: true

- name: Create a file with the output "{{ export_dir }}/{{ unique_code }}/scim.yaml"
  copy:
    content: "{{ get_scim | to_nice_yaml }}"
    dest: "{{ export_dir }}/{{ unique_code }}/scim.yaml"
