galaxy_info:
  author: IBM
  description: Role to get scim config
  company: IBM

  license: Apache

  min_ansible_version: 2.5

  galaxy_tags:
  - isam
  - ibm
  - configure
  - scim
  - v1.0.0

dependencies:
  - start_config