galaxy_info:
  author: Tom Bosmans
  description: Role to download snapshots
  company: IBM

  license: Apache

  min_ansible_version: 2.7

  galaxy_tags:
  - isam
  - ibm
  - create
  - snapshot

dependencies:
  - start_config