---
- hosts: "all"
  connection: local
  gather_facts: yes
  tasks:
    - name: Export AAC Access Control configuration
      tags: ["infomap"]
      import_role:
       name: aac/get_accesscontrol_configuration
