---
- hosts: "all"
  connection: local
  gather_facts: yes
  tasks:
    - name: Export AAC Authentication policies
      tags: ["infomap"]
      import_role:
       name: aac/get_authentication_policies

